services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    app:
        build:
            context: .docker/php
            args:
                UID: 1000
                GID: 1000
        user: "1000:1000"
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: bayarair_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin

    ####################################################################################################
    # Adminer
    ####################################################################################################
    adminer:
        image: adminer
        ports:
            - 9090:8080
        depends_on:
            - db
    mail:
        image: axllent/mailpit:latest
        ports:
            - 8025:8025
            - 1025:1025
# volumes:
#     pgdata:
